security:
#    encoders:
#        # Our user class and the algorithm we'll use to encode passwords
#        # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
#        AppBundle\Entity\User: bcrypt
    encoders:
        Riper\Security\ActiveDirectoryBundle\Security\User\AdUser : plaintext

#    providers:
#        # in this example, users are stored via Doctrine in the database
#        # To see the users at src/AppBundle/DataFixtures/ORM/LoadFixtures.php
#        # To load users from somewhere else: http://symfony.com/doc/current/cookbook/security/custom_provider.html
#        database_users:
#            entity: { class: AppBundle:User, property: username }
    providers:
        active_directory_provider:
              id: riper.security.active.directory.user.provider

    # http://symfony.com/doc/current/book/security.html#firewalls-authentication
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            # this firewall applies to all URLs
            pattern: ^/
            anonymous:  ~
            http_basic: ~
            provider: active_directory_provider
            active_directory:
                login_path: security_login_form
                check_path: security_login_check
                success_handler: login_success_handler
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~
            logout:
                path:   security_logout
                target: homepage

    access_control:
        # this is a catch-all for the admin area
        # additional security lives in the controllers
        #- { path: ^/admin, roles: ROLE_ADMIN }
